version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - run:
          command: curl -X POST "https://api.testproject.io/v2/projects/08yckCJt10WcTeWNvRR9yQ/jobs/U2i09GKYIkmAHawPcP4ibA/run" >
            -H "accept:application/json" >
            -H "Authorization:-Fjk1RhWN1jOk96paFjRZLj9Y8xw1Yvtl1KptDxas8U1">
            -H "Content-Type:application/json">
            -d "{}"
          name: Test

workflows:
  main:
    jobs:
      - build-and-test
