version: 2.1
jobs:
  run-recorded-tests:
    machine:
      image: ubuntu-2004:202010-01
    working_directory: testproject
    steps:
      - run:
          name: Update And Install Dependancies
          command: |
            sudo apt-get -y update
            sudo apt-get install -y curl wget git
            git clone https://github.com/Rantzur1992/recorded_example.git
          
      - run:
          name: Run tests
          command: |
            cd recorded_example
            set -x
            docker-compose up -d

workflows:
  main:
    jobs:
      - run-recorded-tests
